services:
  - type: web
    name: infinito25-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Infinito.wsgi
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.hmfrwzjeqsvnytlripqr:Sh1v@m2005@aws-0-us-east-2.pooler.supabase.com:6543/postgres
