# Generated by Django 5.2 on 2025-04-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('vit_email', models.EmailField(max_length=254, unique=True)),
                ('hostel', models.CharField(max_length=50)),
                ('room_number', models.CharField(max_length=10)),
                ('game_playing', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Chess', 'Chess'), ('Badminton', 'Badminton'), ('Table Tennis', 'Table Tennis'), ('Other', 'Other')], max_length=20)),
            ],
        ),
    ]
