# Generated by Django 5.2 on 2025-04-09 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='game_playing',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Badminton', 'Badminton'), ('Chess', 'Chess'), ('Table Tennis', 'Table Tennis'), ('Throwball', 'Throwball'), ('Carrom', 'Carrom'), ('Squid Games', 'Squid Games'), ('Lemon & Spoon Race', 'Lemon & Spoon Race'), ('Marathon', 'Marathon'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(choices=[('A', 'A Block'), ('B', 'B Block'), ('C', 'C Block'), ('D', 'D Block'), ('E', 'E Block'), ('F', 'F Block'), ('G', 'G Block')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^00\\d{3}\\d{4}$', 'Registration number must be in format 00XXX0000.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='vit_email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@vitstudent\\.ac\\.in$', 'Email must be a valid VIT student email.')]),
        ),
    ]
