# Generated by Django 5.2 on 2025-04-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_student_game_playing_alter_student_hostel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
