# Generated by Django 5.2 on 2025-04-09 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_student_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('^d{2}\\[A-Z]{3}\\d{4}$', 'Registration number must be in format 00XXX0000.')]),
        ),
    ]
