# Generated by Django 5.2 on 2025-04-09 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_student_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{2}[A-Z]{3}\\d{4}$', 'Registration number must be in format 00XXX0000.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='vit_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9._%+-]+@vitstudent\\.ac\\.in$', 'Email must be a valid VIT student email.')]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('registration_number', 'game_playing')},
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('vit_email', 'game_playing'), name='unique_email_game'),
        ),
    ]
