# Generated by Django 5.2 on 2025-04-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_alter_student_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(choices=[('A', 'A Block'), ('B', 'B Block'), ('C', 'C Block'), ('D', 'D Block'), ('E', 'E Block'), ('F', 'F Block'), ('G', 'G Block'), ('H', 'H Block'), ('I', 'I Block'), ('J', 'J Block')], max_length=1),
        ),
    ]
